apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: healthcare-platform
  compliance: hipaa
